// ─── Re-export the Supabase-generated source of truth ────────────────────────
// database.types.ts is auto-generated by `supabase gen types typescript`.
// This file is a convenience layer — import your row types from here, not
// directly from database.types.ts, so if the generated file path ever changes
// you only update one import.

export type { Tables, TablesInsert, TablesUpdate, Enums } from './database.types'

import type { Tables } from './database.types'

// ─── Row type aliases (shorthand) ────────────────────────────────────────────

export type AppUser           = Tables<'users'>
export type Room              = Tables<'rooms'>
export type Contract          = Tables<'contracts'>
export type Invoice           = Tables<'invoices'>
export type Payment           = Tables<'payments'>
export type MaintenanceTicket = Tables<'maintenance_tickets'>
export type TicketReply       = Tables<'ticket_replies'>
export type ExtendRequest     = Tables<'extend_requests'>
export type Report            = Tables<'reports'>

// ─── Joined response types ────────────────────────────────────────────────────
// These match exactly what each API function SELECTs.
// Keeping them here means the API layer and UI code share the same type.

export type ContractWithRelations = Contract & {
  room?:   Pick<Room, 'id' | 'number' | 'price'>
  tenant?: Pick<AppUser, 'id' | 'name' | 'email'>
}

export type InvoiceWithRelations = Invoice & {
  contract?: Pick<Contract, 'id' | 'monthly_rate' | 'status'>
  tenant?:   Pick<AppUser, 'id' | 'name' | 'email'>
}

export type PaymentWithRelations = Payment & {
  invoice?: Pick<Invoice, 'id' | 'due_date' | 'total_amount' | 'billing_month' | 'status'>
  tenant?:  Pick<AppUser, 'id' | 'name' | 'email'>
}

export type TicketWithRelations = MaintenanceTicket & {
  room?:     Pick<Room, 'id' | 'number'>
  reporter?: Pick<AppUser, 'id' | 'name' | 'email'>
  replies?:  (TicketReply & {
    sender?: Pick<AppUser, 'id' | 'name' | 'role'>
  })[]
}
